package dev.atomsdemo.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;
import java.util.List;
import java.util.Map;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

/**
 * DeepSeek OpenAI-compatible API adapter. API keys remain on the server and
 * are supplied only via DEEPSEEK_API_KEY, never sent to the Vue application.
 */
@Service
public class DeepSeekService {
  private final String key, model;
  private final ObjectMapper json = new ObjectMapper();
  private final HttpClient client = HttpClient.newBuilder().connectTimeout(Duration.ofSeconds(15)).build();

  public DeepSeekService(@Value("${atoms.deepseek.api-key}") String key, @Value("${atoms.deepseek.model}") String model) {
    this.key = key;
    this.model = model;
  }

  /** Generates a self-contained page, while retaining a usable local fallback for reviewers without a key. */
  public Result generate(String prompt) {
    if (key == null || key.isBlank()) return new Result(demoHtml(prompt), "Local demo fallback (set DEEPSEEK_API_KEY to use DeepSeek)");
    try {
      String instruction = "You are an expert product engineer. Return ONLY a complete, safe, standalone HTML document (inline CSS and JavaScript allowed). Build a polished responsive interactive web app matching this request: " + prompt;
      Map<String, Object> body = Map.of(
          "model", model,
          "messages", List.of(Map.of("role", "user", "content", instruction)),
          "temperature", 0.7);
      HttpRequest request = HttpRequest.newBuilder(URI.create("https://api.deepseek.com/chat/completions"))
          .header("Content-Type", "application/json")
          .header("Authorization", "Bearer " + key)
          .POST(HttpRequest.BodyPublishers.ofString(json.writeValueAsString(body)))
          .timeout(Duration.ofSeconds(55))
          .build();
      JsonNode root = json.readTree(client.send(request, HttpResponse.BodyHandlers.ofString()).body());
      String html = root.at("/choices/0/message/content").asText();
      if (html.isBlank()) throw new IllegalStateException(root.path("error").path("message").asText("DeepSeek returned no content"));
      return new Result(html.replace("```html", "").replace("```", "").trim(), "DeepSeek · " + model);
    } catch (Exception e) {
      return new Result(demoHtml(prompt), "Local fallback · DeepSeek unavailable: " + e.getMessage());
    }
  }

  /** A deterministic interactive artifact used only when a model key is unavailable. */
  private String demoHtml(String prompt) {
    String safe = prompt.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;");
    return "<!doctype html><html><head><meta charset='utf-8'><style>body{margin:0;font-family:Inter,Arial;background:#101827;color:#edf4ff}.wrap{max-width:760px;margin:60px auto;padding:32px}.tag{color:#7dd3fc;text-transform:uppercase;letter-spacing:2px}.card{background:#19243a;border:1px solid #334765;border-radius:20px;padding:28px;margin-top:22px}button{background:#31d0aa;border:0;border-radius:9px;padding:12px 18px;font-weight:bold;cursor:pointer}.count{font-size:52px;margin:18px 0}</style></head><body><main class='wrap'><div class='tag'>Atoms generated app</div><h1>" + safe + "</h1><section class='card'><p>This interactive preview was generated by the local resilient demo mode.</p><div class='count' id='n'>0</div><button id='progress' type='button'>Make progress</button></section></main><script>document.getElementById('progress').addEventListener('click',function(){var counter=document.getElementById('n');counter.textContent=String(Number(counter.textContent)+1);});</script></body></html>";
  }

  public record Result(String html, String provider) { }
}
