<script setup>
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import './workflow.css'

const user=ref(JSON.parse(localStorage.getItem('atoms-user')||'null'))
const projects=ref([]),active=ref(null),prompt=ref(''),preview=ref(''),busy=ref(false),error=ref('')
const selectedVersion=ref(null)
const form=ref({name:'',email:'',password:''}),authMode=ref('login'),changeType=ref('CREATE')
const trace=ref([]),regression=ref(null),codeOpen=ref(false),code=ref('')
const agentRun=ref(null),planDraft=ref(''); let pollTimer=null
const selectedRun=ref(null)
const stageRank=computed(()=>{const stage=agentRun.value?.stage||'';if(stage==='COMPLETED')return 4;if(stage==='REGRESSION')return 3;if(stage==='GENERATING')return 2;if(stage==='LOADING_CONTEXT')return 1;return 0})
const headers=()=>({'Content-Type':'application/json','X-User-Id':user.value?.id})
function preparePreview(html){return (html||'').replace("onclick='n.textContent=+n.textContent+1'","onclick=\"document.getElementById('n').textContent=String(Number(document.getElementById('n').textContent)+1)\"")}
async function api(url,options={}){const r=await fetch('/api'+url,{...options,headers:{...headers(),...(options.headers||{})}});if(!r.ok){const body=await r.json().catch(()=>({}));throw new Error(body.detail||body.message||body.error||`请求失败（HTTP ${r.status}）`)}return r.status===204?null:r.json()}
async function auth(){error.value='';try{const u=await api('/auth/'+authMode.value,{method:'POST',body:JSON.stringify(form.value)});user.value=u;localStorage.setItem('atoms-user',JSON.stringify(u));await load()}catch(e){error.value=e.message}}
async function load(){projects.value=await api('/projects');if(projects.value.length&&!active.value)await choose(projects.value[0].id)}
async function choose(id){active.value=await api('/projects/'+id);const x=await api('/projects/'+id+'/preview').catch(()=>null);preview.value=preparePreview(x?.html);selectedVersion.value=x?.version||null;prompt.value=active.value.prompt;trace.value=[];regression.value=null;selectedRun.value=null}
async function preparePlan(){if(!prompt.value.trim())return;const requestedPrompt=prompt.value;busy.value=true;error.value='';try{const r=await api('/projects/plan',{method:'POST',body:JSON.stringify({projectId:active.value?.id,prompt:requestedPrompt,changeType:changeType.value})});agentRun.value=r;planDraft.value=r.plan;active.value=null;await load();await choose(r.project_id);prompt.value=requestedPrompt}catch(e){error.value=e.message}finally{busy.value=false}}
async function approvePlan(){if(!agentRun.value)return;busy.value=true;try{await api('/agent-runs/'+agentRun.value.id+'/plan',{method:'PATCH',body:JSON.stringify({plan:planDraft.value})});agentRun.value=await api('/agent-runs/'+agentRun.value.id+'/approve',{method:'POST'});watchRun()}catch(e){error.value=e.message}finally{busy.value=false}}
async function cancelRun(){if(!agentRun.value)return;agentRun.value=await api('/agent-runs/'+agentRun.value.id+'/cancel',{method:'POST'});stopWatching()}
function stopWatching(){if(pollTimer){clearInterval(pollTimer);pollTimer=null}}
async function refreshRun(){if(!agentRun.value)return;try{agentRun.value=await api('/agent-runs/'+agentRun.value.id);if(['COMPLETED','FAILED','CANCELLED'].includes(agentRun.value.status)){stopWatching();if(agentRun.value.status==='COMPLETED'){regression.value={status:agentRun.value.regression?.split(':')[0]||'DONE',summary:agentRun.value.regression||''};await load();await choose(agentRun.value.project_id)}}}catch(e){error.value=e.message;stopWatching()}}
function watchRun(){stopWatching();refreshRun();pollTimer=setInterval(refreshRun,900)}
async function version(v){const x=await api('/projects/'+active.value.id+'/preview?version='+v);preview.value=preparePreview(x.html);selectedVersion.value=x.version}
async function showCode(){if(!active.value)return;const r=await fetch('/api/projects/'+active.value.id+'/code?version='+selectedVersion.value,{headers:{'X-User-Id':user.value.id}});if(!r.ok){error.value='无法读取代码';return}code.value=await r.text();codeOpen.value=true}
async function copyCode(){await navigator.clipboard.writeText(code.value);alert('代码已复制')}
async function exportZip(){if(!active.value)return;const r=await fetch('/api/projects/'+active.value.id+'/export?version='+selectedVersion.value,{headers:{'X-User-Id':user.value.id}});if(!r.ok){error.value='导出失败';return}const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=`atoms-project-${active.value.id}-v${selectedVersion.value}.zip`;a.click();URL.revokeObjectURL(url)}
async function remove(id){if(confirm('删除这个项目及其所有版本？')){await api('/projects/'+id,{method:'DELETE'});active.value=null;preview.value='';await load()}}
function newProject(){active.value=null;preview.value='';prompt.value='';changeType.value='CREATE';trace.value=[];regression.value=null;agentRun.value=null;selectedRun.value=null;stopWatching()}
function logout(){localStorage.removeItem('atoms-user');user.value=null;active.value=null;projects.value=[]}
onMounted(()=>user.value&&load())
onBeforeUnmount(stopWatching)
</script>

<template>
  <main v-if="!user" class="auth-page"><section class="auth-card"><div class="atom">✦</div><p class="eyebrow">ATOMS FORGE</p><h1>把一句想法，变成可体验的产品。</h1><p class="muted">DeepSeek 驱动 · 版本持久化 · 代码可导出</p><div class="tabs"><button :class="{selected:authMode==='login'}" @click="authMode='login'">登录</button><button :class="{selected:authMode==='register'}" @click="authMode='register'">创建账号</button></div><input v-if="authMode==='register'" v-model="form.name" placeholder="你的名字"><input v-model="form.email" placeholder="邮箱" type="email"><input v-model="form.password" placeholder="密码（至少 6 位）" type="password"><p v-if="error" class="error">{{error}}</p><button class="primary wide" @click="auth">{{authMode==='login'?'进入工作台':'开始构建'}}</button></section></main>
  <main v-else class="shell"><aside><div class="brand"><span>✦</span> atoms</div><button class="new" @click="newProject">＋ 新建应用</button><p class="label">你的应用</p><div class="project-list"><button v-for="p in projects" :key="p.id" class="project" :class="{active:p.id===active?.id}" @click="choose(p.id)"><span>{{p.title}}</span><small>{{p.versions||0}} versions</small><i @click.stop="remove(p.id)">×</i></button></div><div class="profile"><b>{{user.name}}</b><span>{{user.email}}</span><button @click="logout">退出</button></div></aside>
    <section class="workspace"><header><div><p class="eyebrow">{{active?'PROJECT / '+active.id:'NEW PROJECT'}}</p><h2>{{active?.title||'开始一个新构想'}}</h2></div><span class="status" :class="active?.status?.toLowerCase()">{{active?.status||'DRAFT'}}</span></header>
      <section class="composer"><div class="composer-head"><label>本次改动</label><select v-model="changeType" :disabled="agentRun&&agentRun.status==='RUNNING'"><option value="CREATE">创建应用</option><option value="MODIFY" :disabled="!active">增量修改（保留功能）</option><option value="BUGFIX" :disabled="!active">修复 Bug（执行回归检查）</option></select></div><textarea v-model="prompt" :disabled="agentRun&&agentRun.status==='RUNNING'" :placeholder="changeType==='BUGFIX'?'例如：手机号输入 abc 仍预约成功，请修复且不要影响菜单筛选。':'描述想创建或修改的功能…'" @keydown.meta.enter="preparePlan"/><div><span>{{active&&changeType!=='CREATE'?'将携带当前代码与最近 8 条历史需求':'先生成计划，再人工批准执行'}}</span><button class="primary" :disabled="busy||(agentRun&&agentRun.status==='RUNNING')" @click="preparePlan">{{busy?'正在准备…':'✦ 生成计划'}}</button></div></section>
      <section class="stages"><div :class="{stageActive:stageRank===1,stageDone:stageRank>1}"><b>01</b><span>理解需求</span><small>{{stageRank>0?'已完成':'等待中'}}</small></div><div :class="{stageActive:stageRank===2,stageDone:stageRank>2}"><b>02</b><span>设计页面</span><small>{{stageRank>1?'已完成':'等待中'}}</small></div><div :class="{stageActive:stageRank===3,stageDone:stageRank>3}"><b>03</b><span>生成预览</span><small>{{stageRank>2?'已完成':'等待中'}}</small></div></section>
      <section v-if="agentRun" class="agent-flow"><div class="flow-title"><b>Agent Run #{{agentRun.id}}</b><span :class="'run-'+agentRun.status.toLowerCase()">{{agentRun.stage}}</span></div><p v-if="agentRun.status==='PLAN_READY'">请审阅或编辑计划，批准后才会调用模型生成代码。</p><textarea v-if="agentRun.status==='PLAN_READY'" v-model="planDraft" class="plan-editor"/><ol class="flow-trace"><li v-for="item in (agentRun.trace||'').split('\n').filter(Boolean)" :key="item">{{item}}</li></ol><div class="flow-actions" v-if="agentRun.status==='PLAN_READY'"><button class="primary" :disabled="busy" @click="approvePlan">批准并执行</button><button class="utility" @click="cancelRun">取消计划</button></div><div class="flow-actions" v-else-if="agentRun.status==='RUNNING'"><button class="utility" @click="cancelRun">取消执行</button></div><p v-if="agentRun.status==='FAILED'" class="error">任务失败，请修改计划或重新创建任务。</p></section>
      <section v-if="trace.length" class="agent-log"><b>本次执行记录</b><ol><li v-for="item in trace" :key="item">{{item}}</li></ol></section><section v-if="regression" class="regression" :class="regression.status.toLowerCase()"><b>回归检查 · {{regression.status}}</b><span>{{regression.summary}}</span></section>
      <p v-if="error" class="error workspace-error">{{error}}</p><section v-if="active" class="versions"><span>版本历史</span><button v-for="g in active.generations" :key="g.id" :class="{selectedVersion:g.version===selectedVersion}" @click="version(g.version)">v{{g.version}} · {{g.provider?.startsWith('DeepSeek ·')?'DeepSeek':'Local fallback'}}</button><span class="grow"/><button class="utility" @click="showCode">查看代码</button><button class="utility" @click="exportZip">ZIP 导出</button></section>
      <section v-if="codeOpen" class="code-panel"><div><b>生成代码</b><span><button @click="copyCode">复制</button><button @click="codeOpen=false">关闭</button></span></div><pre>{{code}}</pre></section>
      <section v-if="active?.agentRuns?.length" class="history-panel"><div class="history-title"><b>修改历史</b><span>{{active.agentRuns.length}} 次记录</span></div><button v-for="run in active.agentRuns" :key="run.id" class="history-item" :class="{historySelected:selectedRun?.id===run.id}" @click="selectedRun=selectedRun?.id===run.id?null:run"><span class="history-dot"></span><span class="history-main"><b>{{run.change_type==='BUGFIX'?'Bug 修复':run.change_type==='MODIFY'?'增量修改':'创建应用'}}</b><small>{{run.prompt}}</small></span><span class="history-status">{{run.status}}</span></button><div v-if="selectedRun" class="history-detail"><p><b>实施计划</b></p><pre>{{selectedRun.plan}}</pre><p><b>执行记录</b></p><ol><li v-for="line in (selectedRun.trace||'').split('\n').filter(Boolean)" :key="line">{{line}}</li></ol><p v-if="selectedRun.regression"><b>回归结果：</b>{{selectedRun.regression}}</p></div></section>
    </section>
    <section class="preview"><div class="previewbar"><span class="dot"></span><span class="dot"></span><span class="dot"></span><b>Live Preview</b><span v-if="selectedVersion">v{{selectedVersion}}</span><span v-if="active">{{active.status}}</span></div><iframe v-if="preview" :srcdoc="preview" sandbox="allow-scripts allow-forms" title="Generated application"/><div v-else class="empty"><div>✦</div><h3>你的作品将在这里诞生</h3><p>创建应用或选择历史项目，即可预览可交互版本。</p></div></section>
  </main>
</template>
